"""accounts field deleted

Revision ID: f1ea8b784ecb
Revises: cfd8f3b80f6e
Create Date: 2026-05-27 20:24:55.936691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1ea8b784ecb"
down_revision: Union[str, Sequence[str], None] = "cfd8f3b80f6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("current_balance", sa.Numeric(precision=12, scale=2), nullable=False),
    )
    op.drop_column("accounts", "opening_balance")
    op.drop_column("accounts", "opening_balance_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "opening_balance_date", sa.DATE(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "accounts",
        sa.Column(
            "opening_balance",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("accounts", "current_balance")
    # ### end Alembic commands ###
