"""add to_account_id for transfers, make category_id nullable

Revision ID: f9504b1577ca
Revises: 7c5bae8afa9a
Create Date: 2026-06-06 14:22:21.473281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9504b1577ca'
down_revision: Union[str, Sequence[str], None] = '7c5bae8afa9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('to_account_id', sa.UUID(), nullable=True))
    op.alter_column('transactions', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_transactions_to_account_id'), 'transactions', ['to_account_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'accounts', ['to_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_to_account_id'), table_name='transactions')
    op.alter_column('transactions', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('transactions', 'to_account_id')
    # ### end Alembic commands ###
